import React, { useState } from 'react';
import { hashFile, importPublicKey, verifySignature } from '../services/rsaService';

const DocumentVerifier: React.FC = () => {
  const [file, setFile] = useState<File | null>(null);
  const [publicKeyPem, setPublicKeyPem] = useState('');
  // For demo, we paste the string generated by the Signer (simulate QR Scan)
  const [qrString, setQrString] = useState('');
  
  const [status, setStatus] = useState<'IDLE' | 'VERIFYING' | 'VALID' | 'INVALID' | 'ERROR'>('IDLE');
  const [errorMsg, setErrorMsg] = useState('');

  const handleVerify = async () => {
    setStatus('VERIFYING');
    setErrorMsg('');

    try {
        if (!file || !publicKeyPem || !qrString) throw new Error("Missing inputs");

        // 1. Parse QR Data (Format: HASH|SALT|SIG)
        const parts = qrString.split('|');
        if (parts.length !== 3) throw new Error("Invalid Signature Data format");
        
        const [claimedHash, salt, signatureHex] = parts;

        // 2. Re-calculate File Hash
        const actualHash = await hashFile(file);

        // 3. Immediate Hash Check (Fast Fail)
        if (actualHash !== claimedHash) {
            setStatus('INVALID');
            setErrorMsg("Document integrity check failed. File hash does not match signature metadata.");
            return;
        }

        // 4. Import Public Key
        const publicKey = await importPublicKey(publicKeyPem);

        // 5. Verify RSA Signature
        // We verify that the Signature was created using PrivateKey on (actualHash + salt)
        const isValid = await verifySignature(publicKey, signatureHex, actualHash, salt);

        if (isValid) {
            setStatus('VALID');
        } else {
            setStatus('INVALID');
            setErrorMsg("Cryptographic signature invalid. The key does not match or data was tampered.");
        }

    } catch (err: any) {
        console.error(err);
        setStatus('ERROR');
        setErrorMsg(err.message || "Verification process error");
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto bg-slate-800 p-8 rounded-xl border border-slate-700 shadow-xl">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2 mb-6">
            <span className="text-brand-400">04.</span> Verify Signature
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
                 <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-2">1. Original Document</label>
                    <input 
                        type="file" 
                        onChange={(e) => {
                            if (e.target.files?.[0]) {
                                setFile(e.target.files[0]);
                                setStatus('IDLE');
                            }
                        }}
                        className="block w-full text-sm text-slate-400
                        file:mr-4 file:py-2 file:px-4
                        file:rounded-full file:border-0
                        file:text-sm file:font-semibold
                        file:bg-slate-700 file:text-brand-400
                        hover:file:bg-slate-600 cursor-pointer"
                    />
                </div>

                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-2">2. Signer's Public Key (PEM)</label>
                    <textarea
                        value={publicKeyPem}
                        onChange={(e) => setPublicKeyPem(e.target.value)}
                        placeholder="-----BEGIN PUBLIC KEY-----..."
                        className="w-full h-24 bg-slate-900 border border-slate-600 rounded p-2 text-xs font-mono text-slate-300 focus:outline-none focus:border-brand-500"
                    />
                </div>

                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-2">3. Signature Data (Scan QR)</label>
                    <textarea
                        value={qrString}
                        onChange={(e) => setQrString(e.target.value)}
                        placeholder="Paste text scanned from QR Code (HASH|SALT|SIG)"
                        className="w-full h-24 bg-slate-900 border border-slate-600 rounded p-2 text-xs font-mono text-slate-300 focus:outline-none focus:border-brand-500"
                    />
                </div>

                <button
                    onClick={handleVerify}
                    disabled={status === 'VERIFYING'}
                    className="w-full bg-brand-600 hover:bg-brand-500 text-white font-bold py-3 rounded shadow transition-all"
                >
                    {status === 'VERIFYING' ? 'Verifying...' : 'Verify Authenticity'}
                </button>
            </div>

            <div className="flex flex-col items-center justify-center bg-slate-900 rounded-lg border border-slate-700 p-6">
                {status === 'IDLE' && (
                    <div className="text-slate-500 text-center">
                        <svg className="w-12 h-12 mx-auto mb-2 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                        <p>Ready to verify</p>
                    </div>
                )}
                
                {status === 'VALID' && (
                     <div className="text-center animate-bounce-short">
                        <div className="w-20 h-20 bg-green-500/20 rounded-full flex items-center justify-center mx-auto mb-4 border-2 border-green-500">
                             <svg className="w-10 h-10 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7"></path></svg>
                        </div>
                        <h3 className="text-2xl font-bold text-white mb-1">VALID SIGNATURE</h3>
                        <p className="text-green-400">Document is authentic and unaltered.</p>
                     </div>
                )}

                {status === 'INVALID' && (
                     <div className="text-center">
                        <div className="w-20 h-20 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4 border-2 border-red-500">
                             <svg className="w-10 h-10 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M6 18L18 6M6 6l12 12"></path></svg>
                        </div>
                        <h3 className="text-2xl font-bold text-white mb-1">INVALID</h3>
                        <p className="text-red-400 text-sm max-w-xs mx-auto">{errorMsg}</p>
                     </div>
                )}

                {status === 'ERROR' && (
                     <div className="text-center">
                        <p className="text-yellow-500 font-bold mb-2">System Error</p>
                        <p className="text-slate-400 text-xs">{errorMsg}</p>
                     </div>
                )}
            </div>
        </div>
    </div>
  );
};

export default DocumentVerifier;